.autodepend

# Makefile

ARCH = arch\msdos

BINDIR = ..\BIN

TPC = TPC -M -L -E$(BINDIR) -I..\QUICKCRT -U$(BINDIR);..\QUICKCRT

efntdsgn: efntdsgn.exe	

efnttools: qfntload.exe qfnt2raw.exe raw2qfnt.exe qfnt2tsr.exe

all: efntdsgn efnttools qdetune.exe qkeys.exe qnothing.exe qcnftool.exe qscroll.exe

.pas.tpu: 
    @if not exist $(BINDIR) mkdir $(BINDIR)
	$(TPC) $*.pas

.pas.exe: 
    @if not exist $(BINDIR) mkdir $(BINDIR)
	$(TPC) $*.pas
