{ Copyright 2015 Jerome Shidel }

(* 
		
	This project and related files are subject to either the terms
	specified in the included LICENSE.TXT file or the GNU GPLv2.0.
	
*)

{$I ETOOLS.DEF}
program Eternity_Audio_Tool; { X Series }

{uses QObjects;}

{$I ..\ETERNITY\LICENSE.INC}

const
	AppTitle = 'Eternity PC Speaker Audio Utility';
	AppID = 'QDETUNE';

	
begin
	WriteLn('Placeholder application for ' + AppTitle);
end.
