{ Copyright 2015 Jerome Shidel }

(* 
		
	This project and related files are subject to either the terms
	specified in the included LICENSE.TXT file or the GNU GPLv2.0.
	
*)

{$I ETOOLS.DEF}
program Eternity_Font_Convert_from_RAW_data; { X Series }

{$I ..\ETERNITY\LICENSE.INC}

const
	AppTitle = 'QuickCrt Raw to Font Converter';
	AppID = 'QRAW2FNT';
		
procedure Execute;
begin
end;
		 
begin
	Execute; 
end.
