.autodepend

# Makefile

ARCH = arch\msdos

ARCH = arch\msdos

BINDIR = BIN

TPC = TPC -M -L -E$(BINDIR) -U$(BINDIR);

QCRT_FILES = \
	QCRT.TPU \
	QSTRINGS.TPU \
	QERRORS.TPU \
	QDOS.TPU \
	QBIOS.TPU \
	QFILES.TPU \
	QDIR.TPU \
	QVESA.TPU \
	QOBJECTS.TPU 
	
templates: 
	COPY TEMPLATE.ON TEMPLATE.DEF
	
notemplates: 
	COPY TEMPLATE.OFF TEMPLATE.DEF
	
qtest:
	make -S qtest.exe
	$(BINDIR)\QTEST.EXE

quickcrt: $(QCRT_FILES)

qcrt: QOBJECTS.PAS

.pas.tpu: 
    @if not exist $(BINDIR) mkdir $(BINDIR)
	$(TPC) $*.pas

.pas.exe: 
    @if not exist $(BINDIR) mkdir $(BINDIR)
	$(TPC) $*.pas
	
.pas.bin: 
    @if not exist $(BINDIR) mkdir $(BINDIR)
	$(TPC) $*.pas
	copy $(BINDIR)\$*.EXE $(BINDIR)\$*.BIN
	del $(BINDIR)\$*.EXE
